#!/bin/bash

conda create --name ml -y

conda activate ml
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia -y
conda install pip -y

pip install jupyter
pip install transformers diffusers invisible-watermark
pip install scipy ftfy "ipywidgets>=7,<8" pillow einops einops-exts resize-right
pip install datasets sentencepiece matplotlib
